CREATE TABLE IF NOT EXISTS web_users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_color VARCHAR(50) DEFAULT '#6366f1',
    default_format VARCHAR(50) DEFAULT 'video',
    default_quality VARCHAR(50) DEFAULT 'best',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_downloads ADD COLUMN IF NOT EXISTS web_user_id INTEGER REFERENCES web_users(id) ON DELETE SET NULL;
