name: Deploy to VPS Server

on:
  push:
    branches:
      - main  # Kodlaringizni 'main' branchiga yuborganingizda avtomatik ishga tushadi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH orqali ulanish va Deploy qilish
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Serverdagi loyiha papkasiga o'tish
            cd /app/yt-downloader
            
            # Yangi o'zgarishlarni tortib olish
            git pull origin main
            
            # Konteynerlarni yangilab qayta qurish
            docker compose up -d --build
